### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by xuwei1245645564** [fshamshirdar/DeepVO#2]
Hello! The training set I use is 00, 02, 05, 08. I don’t know what the reason is during training. There are always more than 1 pictures not trained. Do you know what the reason is?

**Comment by fshamshirdar** [comment]
Hi, I am sorry but I didn't get your question. Are there some samples from the dataset that are not used during training?

**Comment by xuwei1245645564** [comment]
Yes, as you said. Also want to ask what is the sequence of your training and testing?What do the values that are output during the test mean?

**Comment by fshamshirdar** [comment]
"Yes, as you said"

There could be bugs in dataset.py regarding ignoring some training data which I believe is not more than 2 sample for each record.

"Also want to ask what is the sequence of your training and testing?"

The network has LSTM cells to model dynamics and temporality, and this requires sequential training. Sequence length is an arbitrary number in each epoch.

"What do the values that are output during the test mean?"

Didn't quite get the question. But the output of the model is 6DoF odometry estimation.

**Comment by xuwei1245645564** [comment]
Thanks, your answer. 

“Sequence length is an arbitrary number in each epoch”
I don't get this said.

The output of the model  is  “print(estimated_odometries, odometries_stacked)”. and I don't understand the value "odometries_stacked"?
