### ISSUE TITLE
image_2

### ISSUE THREAD

**Issue by surajmahangade** [fshamshirdar/DeepVO#5]
https://github.com/fshamshirdar/DeepVO/blob/7a8e73f2a3558aabbca26f8235061c15f77f4c5c/dataset.py#L61
In this line the folder referenced is image_2 but when I downloaded the KITTI dataset I only get image_0 and image_1 folder.
Can you help?

Thank you

**Comment by paaraujo** [comment]
@surajmahangade you should download the color dataset (http://www.cvlibs.net/download.php?file=data_odometry_color.zip)

**Comment by surajmahangade** [comment]
Thank you
